# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages
name: Publish Package to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: publish
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - name: Update NPM
        run: |
          npm i -g npm@latest
          npm --version
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
